"""
Step 5b closure: encode `TERM.CMF`'s default ("automatic") closure as a
fix/free split over the JuMP variables built by `build_model!`/`build_model_full!`.

`TERM.CMF` (`origin/TERM.CMF`, lines 21-68) lists 48 `Exogenous` names generated by
GEMPACK's TABmate Tools, followed by `Rest endogenous;`. Six of those 48
(`delfwage_o`, `delUnity`, `emptrend`, `frnorm`, `frnorm_id`, `gtrend`) belong to the
Excerpt 50-54 dynamic extension and are not declared as JuMP variables yet (no
`build_dynamics!.jl` — Step 6, still pending) — they're simply skipped here.

This module intentionally does NOT apply any of `TERM.CMF`'s `swap` statements
(the active numeraire swap `phi = Natmacro("GDPPI")`, or the dynamic-closure swaps
for `xhouhtot`/`houslack`/`fgovtot`/`xcap`/`finv1`/`delfwage`): the numeraire swap
needs `Natmacro("GDPPI")`, a national-aggregate reporting variable from Excerpts
30-40 that isn't built (out of Step 5's scope by design — see PLAN.md), and the
closure swaps need Step 6 dynamic variables. What's implemented here is the base
*static* closure — `phi` (the exchange rate) is left as the (default) numeraire,
fixed at its benchmark value. Step 6 can layer its own swaps on top once
`build_dynamics!.jl` exists.
"""

# TERM.CMF Exogenous list, scalar-shaped variables (`@variable(m, name)`, no index)
const BASE_CLOSURE_SCALARS = [
    "blabnat", "bprimnat", "capslack", "fgovgen", "flab_iod", "houslack",
    "invslack", "natfpexp", "natfqexp", "phi",
]

# TERM.CMF Exogenous list, array-shaped variables (`@variable(m, name[...])`)
const BASE_CLOSURE_ARRAYS = [
    "acap", "alnd", "atot", "atrad", "atradmar", "bint_scd", "blab",
    "blab_d", "bprim", "bprim_d", "delPTXRATE", "fgov", "fgovtot",
    "fgov_s", "finv1", "flabsupA", "flabsup_id", "flab_id", "flab_io",
    "fpexp", "fpexp_d", "fqexp", "fqexp_d", "nhou", "pfimp", "srctwist",
    "tuser_su", "tuser_sud", "tuser_ud", "xcap", "xhouhtot", "xlnd",
]

# Names in TERM.CMF's default Exogenous list that are Step 6 (dynamic, Excerpts
# 50-54) scope and are not declared as variables yet — kept here only so the
# omission is documented and greppable, not silently dropped.
const DYNAMIC_ONLY_CLOSURE_NAMES = [
    "delfwage_o", "delUnity", "emptrend", "frnorm", "frnorm_id", "gtrend",
]

_varrefs(v::VariableRef) = (v,)
_varrefs(v::AbstractArray) = v

"""
    initialize_model!(m, vars; shocks=Dict())

Fix every variable named in `BASE_CLOSURE_SCALARS`/`BASE_CLOSURE_ARRAYS` at its
shock value (default `0.0` — a benchmark run with no shock replicates the base
data exactly), leave every other declared variable free for Ipopt to solve, and
set a `0.0` start value on every variable (the correct starting guess for a
%-change formulation with all-benchmark data).

`shocks` maps a closure variable name to either a scalar (applied to every
element) or an array matching that variable's shape (applied element-wise) —
e.g. `Dict("blabnat" => -3.0)` for `TERM.CMF`'s `Shock blabnat = -3;`.
"""
function initialize_model!(m::JuMP.Model, vars::Dict{String,Any}; shocks::Dict{String,Any}=Dict{String,Any}())
    for (_, v) in vars
        for vr in _varrefs(v)
            JuMP.set_start_value(vr, 0.0)
        end
    end

    for nm in BASE_CLOSURE_SCALARS
        haskey(vars, nm) || continue
        val = get(shocks, nm, 0.0)
        JuMP.fix(vars[nm], val; force=true)
    end

    for nm in BASE_CLOSURE_ARRAYS
        haskey(vars, nm) || continue
        v = vars[nm]
        shock = get(shocks, nm, 0.0)
        for idx in eachindex(v)
            val = shock isa AbstractArray ? shock[idx] : shock
            JuMP.fix(v[idx], val; force=true)
        end
    end

    return m
end
